name: Deploy FastAPI App

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Install sshpass
      - name: Install sshpass
        run: sudo apt-get install sshpass

      # Step 3: Deploy application
      - name: Deploy application
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd $(pwd)  
          git pull origin main
          chmod +x deploy.sh
          ./deploy.sh
          EOF
